package pojosbotanica;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;

public class Operaciones {
    public static final int INSERTAR_USUARIO = 1;
    public static final int ELIMINAR_USUARIO = 2;
    public static final int MODIFICAR_USUARIO = 3;
    public static final int LEER_USUARIO = 4;
    public static final int LEER_USUARIOS = 5;
    public static final int INSERTAR_RESENA = 6;
    public static final int ELIMINAR_RESENA = 7;
    public static final int MODIFICAR_RESENA = 8;
    public static final int LEER_RESENA = 9;
    public static final int LEER_RESENAS = 10;
    public static final int INSERTAR_INSECTO = 11;
    public static final int ELIMINAR_INSECTO = 12;
    public static final int MODIFICAR_INSECTO = 13;
    public static final int LEER_INSECTO = 14;
    public static final int LEER_INSECTOS = 15;
    public static final int INSERTAR_PLANTA = 16;
    public static final int ELIMINAR_PLANTA = 17;
    public static final int MODIFICAR_PLANTA = 18;
    public static final int LEER_PLANTA = 19;
    public static final int LEER_PLANTAS = 20;
    public static final int INSERTAR_GUIA = 21;
    public static final int ELIMINAR_GUIA = 22;
    public static final int MODIFICAR_GUIA = 23;
    public static final int LEER_GUIA = 24;
    public static final int LEER_GUIAS = 25;
    public static final int INSERTAR_INTERES = 26;
    public static final int ELIMINAR_INTERES = 27;
    public static final int MODIFICAR_INTERES = 28;
    public static final int LEER_INTERES = 29;
    public static final int LEER_INTERESES = 30;
    public static final int INSERTAR_INSECTO_PLANTA = 31;
    public static final int ELIMINAR_INSECTO_PLANTA = 32;
    public static final int LEER_INSECTOS_PLANTA = 33;
    public static final int INSERTAR_USUARIO_PLANTA = 34;
    public static final int ELIMINAR_USUARIO_PLANTA = 35;
    public static final int LEER_USUARIOS_PLANTA = 36;
}
